import React, { useState, useEffect } from "react";
import { Connection, PublicKey, Transaction, SystemProgram } from "@solana/web3.js";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { useWallet } from "@solana/wallet-adapter-react";

// shadcn/ui components
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

const SOLANA_RPC = "https://api.mainnet-beta.solana.com";
const connection = new Connection(SOLANA_RPC);

const currencyRates = {
  USDT: 1,
    USDC: 1,
      SOL: 25,
      };

      export default function Purchase() {
        const { publicKey, connected, sendTransaction } = useWallet();

          const [balance, setBalance] = useState(null);
            const [amount, setAmount] = useState("");
              const [frep, setFrep] = useState(0);
                const [currency, setCurrency] = useState("USDT");

                  const priceFrep = 0.001;

                    useEffect(() => {
                        if (connected && publicKey) {
                              connection.getBalance(publicKey).then((lamports) => setBalance(lamports / 1e9));
                                  }
                                    }, [connected, publicKey]);

                                      useEffect(() => {
                                          const calcFrep = () => {
                                                if (amount) {
                                                        const rate = currencyRates[currency] || 1;
                                                                setFrep((amount * rate) / priceFrep);
                                                                      } else setFrep(0);
                                                                          };
                                                                              calcFrep();
                                                                                  const interval = setInterval(calcFrep, 15000);
                                                                                      return () => clearInterval(interval);
                                                                                        }, [amount, currency]);

                                                                                          const handleBuy = async () => {
                                                                                              if (!connected || !publicKey || !amount || amount <= 0) return;

                                                                                                  try {
                                                                                                        const lamports = currency === "SOL" ? amount * 1e9 : 0;
                                                                                                              const transaction = new Transaction().add(
                                                                                                                      SystemProgram.transfer({
                                                                                                                                fromPubkey: publicKey,
                                                                                                                                          toPubkey: new PublicKey("DESTINATION_WALLET_ADDRESS"),
                                                                                                                                                    lamports,
                                                                                                                                                            })
                                                                                                                                                                  );
                                                                                                                                                                        const signature = await sendTransaction(transaction, connection);
                                                                                                                                                                              await connection.confirmTransaction(signature, "confirmed");
                                                                                                                                                                                    alert("تم شراء FREP بنجاح!");
                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                              console.error(error);
                                                                                                                                                                                                    alert("فشل الشراء: " + error.message);
                                                                                                                                                                                                        }
                                                                                                                                                                                                          };

                                                                                                                                                                                                            return (
                                                                                                                                                                                                                <div className="min-h-screen flex flex-col items-center p-6 bg-gradient-to-b from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800">
                                                                                                                                                                                                                      
                                                                                                                                                                                                                            {/* Header */}
                                                                                                                                                                                                                                  <div className="flex flex-col sm:flex-row w-full justify-between items-center max-w-4xl mb-10 gap-4">
                                                                                                                                                                                                                                          <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 text-transparent bg-clip-text">
                                                                                                                                                                                                                                                    FREP Launchpad
                                                                                                                                                                                                                                                            </h1>
                                                                                                                                                                                                                                                                    <WalletMultiButton />
                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                {/* Wallet Info */}
                                                                                                                                                                                                                                                                                      {connected && publicKey && (
                                                                                                                                                                                                                                                                                              <Card className="mb-8 w-full max-w-md">
                                                                                                                                                                                                                                                                                                        <CardContent className="flex flex-col gap-2 text-sm pt-4">
                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                  Wallet:{" "}
                                                                                                                                                                                                                                                                                                                                                <span className="font-mono">
                                                                                                                                                                                                                                                                                                                                                                {publicKey.toBase58().slice(0, 6)}...{publicKey.toBase58().slice(-4)}
                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                                                                                    Balance:{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {balance !== null ? `${balance.toFixed(3)} SOL` : "..."}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Calculator Card */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Card className="w-full max-w-md shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardTitle className="text-center">شراء FREP</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-center text-sm text-muted-foreground">(1 FREP = 0.001$)</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </CardHeader>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <CardContent className="flex flex-col gap-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Currency Tabs */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Tabs value={currency} onValueChange={setCurrency} className="w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <TabsList className="grid grid-cols-3 w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {["USDT", "USDC", "SOL"].map((c) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <TabsTrigger key={c} value={c}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {c}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </TabsTrigger>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </TabsList>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Tabs>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Amount Input */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder={`Amount in ${currency}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* FREP Result */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-center font-bold text-xl bg-muted p-2 rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              FREP: {frep.toFixed(3)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </CardContent>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <CardFooter>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={handleBuy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          disabled={!connected || !amount || amount <= 0}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            شراء الآن
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </CardFooter>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }