import React, { useState, useEffect } from "react";
import { Connection, PublicKey, Transaction, SystemProgram } from "@solana/web3.js";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { useWallet } from "@solana/wallet-adapter-react";
import "../App.css";

const SOLANA_RPC = "https://api.mainnet-beta.solana.com";
const connection = new Connection(SOLANA_RPC);

const currencyRates = {
  USDT: 1,
    USDC: 1,
      SOL: 25,
      };

      export default function Purchase() {
        const { publicKey, connected, sendTransaction } = useWallet();

          const [balance, setBalance] = useState(null);
            const [amount, setAmount] = useState("");
              const [frep, setFrep] = useState(0);
                const [currency, setCurrency] = useState("USDT");

                  const priceFrep = 0.001;

                    useEffect(() => {
                        if (connected && publicKey) {
                              connection.getBalance(publicKey).then((lamports) => setBalance(lamports / 1e9));
                                  }
                                    }, [connected, publicKey]);

                                      useEffect(() => {
                                          const calcFrep = () => {
                                                if (amount) {
                                                        const rate = currencyRates[currency] || 1;
                                                                setFrep((amount * rate) / priceFrep);
                                                                      } else setFrep(0);
                                                                          };
                                                                              calcFrep();
                                                                                  const interval = setInterval(calcFrep, 15000);
                                                                                      return () => clearInterval(interval);
                                                                                        }, [amount, currency]);

                                                                                          const handleBuy = async () => {
                                                                                              if (!connected || !publicKey || !amount || amount <= 0) return;

                                                                                                  try {
                                                                                                        const lamports = currency === "SOL" ? amount * 1e9 : 0;
                                                                                                              const transaction = new Transaction().add(
                                                                                                                      SystemProgram.transfer({
                                                                                                                                fromPubkey: publicKey,
                                                                                                                                          toPubkey: new PublicKey("DESTINATION_WALLET_ADDRESS"),
                                                                                                                                                    lamports,
                                                                                                                                                            })
                                                                                                                                                                  );
                                                                                                                                                                        const signature = await sendTransaction(transaction, connection);
                                                                                                                                                                              await connection.confirmTransaction(signature, "confirmed");
                                                                                                                                                                                    alert("تم شراء FREP بنجاح!");
                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                              console.error(error);
                                                                                                                                                                                                    alert("فشل الشراء: " + error.message);
                                                                                                                                                                                                        }
                                                                                                                                                                                                          };

                                                                                                                                                                                                            return (
                                                                                                                                                                                                                <div className="min-h-screen flex flex-col items-center justify-start p-6 bg-gradient-to-b from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800 text-gray-900 dark:text-white">

                                                                                                                                                                                                                      {/* Header */}
                                                                                                                                                                                                                            <div className="flex flex-col sm:flex-row w-full justify-between items-center max-w-4xl mb-10 gap-4">
                                                                                                                                                                                                                                    <h1 className="text-3xl font-bold text-center sm:text-left text-gradient bg-clip-text text-transparent from-purple-400 via-pink-500 to-red-500">
                                                                                                                                                                                                                                              FREP Launchpad
                                                                                                                                                                                                                                                      </h1>
                                                                                                                                                                                                                                                              <WalletMultiButton className="bg-purple-600 hover:bg-purple-700 text-white px-5 py-2 rounded-xl shadow-lg transition-all duration-300" />
                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                          {/* Wallet Info */}
                                                                                                                                                                                                                                                                                {connected && publicKey && (
                                                                                                                                                                                                                                                                                        <div className="mb-8 w-full max-w-md p-5 bg-white dark:bg-gray-800 rounded-xl shadow-lg flex flex-col items-center gap-2 transition-transform transform hover:scale-105">
                                                                                                                                                                                                                                                                                                  <p className="text-sm">
                                                                                                                                                                                                                                                                                                              Connected Wallet:{" "}
                                                                                                                                                                                                                                                                                                                          <span className="font-mono">{publicKey.toBase58().slice(0, 6)}...{publicKey.toBase58().slice(-4)}</span>
                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                              <p className="text-sm">
                                                                                                                                                                                                                                                                                                                                                          Balance: <span className="font-semibold">{balance !== null ? `${balance.toFixed(3)} SOL` : "..."}</span>
                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                        {/* Calculator Card */}
                                                                                                                                                                                                                                                                                                                                                                                              <div className="max-w-md w-full p-6 mb-8 bg-gradient-to-b from-white to-gray-100 dark:from-gray-800 dark:to-gray-700 border border-gray-200 dark:border-gray-600 rounded-2xl shadow-2xl flex flex-col items-center gap-5">
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                              {/* Icons */}
                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-center gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                <img src="/icons/usdt.png" alt="USDT" className="w-10 h-10 hover:scale-110 transition-transform" />
                                                                                                                                                                                                                                                                                                                                                                                                                                          <img src="/icons/usdc.png" alt="USDC" className="w-10 h-10 hover:scale-110 transition-transform" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src="/icons/sol.png" alt="SOL" className="w-10 h-10 hover:scale-110 transition-transform" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Price */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-center font-medium text-lg">(1FREP = 0.001$)</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Currency Selector */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex justify-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {["USDT", "USDC", "SOL"].map((c) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key={c}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => setCurrency(c)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className={`px-5 py-2 rounded-xl font-semibold transition-colors ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            currency === c ? "bg-purple-600 text-white shadow-lg" : "bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {c}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Amount Input */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder={`Amount in ${currency}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full px-5 py-3 rounded-xl border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-black dark:text-white shadow-inner focus:outline-none focus:ring-2 focus:ring-purple-500 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* FREP Display */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-center font-bold text-xl w-full bg-gray-200 dark:bg-gray-700 rounded-xl py-2 shadow-inner">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      FREP: {frep.toFixed(3)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Buy Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={handleBuy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={!connected || !amount || amount <= 0}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className={`w-full py-3 rounded-xl font-bold text-white text-lg transition-all ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        !connected || !amount || amount <= 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? "bg-gray-400 cursor-not-allowed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : "bg-purple-600 hover:bg-purple-700 shadow-lg transform hover:scale-105"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                شراء الآن
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }