import React, { useState, useEffect } from "react";
import { Connection, PublicKey } from "@solana/web3.js";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { useWallet } from "@solana/wallet-adapter-react";
import { Sun, Moon } from "lucide-react";
import "../App.css";

const SOLANA_RPC = "https://api.mainnet-beta.solana.com";
const connection = new Connection(SOLANA_RPC);

export default function Purchase() {
  const { publicKey, connected } = useWallet();
    const [balance, setBalance] = useState(null);
      const [theme, setTheme] = useState("light");
        const [network, setNetwork] = useState("solana");
          const [amount, setAmount] = useState("");
            const [frep, setFrep] = useState(0);

              const toggleTheme = () => {
                  setTheme(theme === "light" ? "dark" : "light");
                      document.documentElement.classList.toggle("dark");
                        };

                          useEffect(() => {
                              if (connected && publicKey) {
                                    connection.getBalance(publicKey).then((lamports) => {
                                            setBalance(lamports / 1e9);
                                                  });
                                                      }
                                                        }, [connected, publicKey]);

                                                          useEffect(() => {
                                                              if (amount) {
                                                                    setFrep(amount / 0.001);
                                                                        } else {
                                                                              setFrep(0);
                                                                                  }
                                                                                    }, [amount]);

                                                                                      const availableNetworks = ["solana", "ethereum", "bsc"];

                                                                                        return (
                                                                                            <div
                                                                                                  className={`min-h-screen flex flex-col items-center p-6 transition ${
                                                                                                          theme === "dark" ? "bg-gray-900 text-white" : "bg-gray-50 text-gray-900"
                                                                                                                }`}
                                                                                                                    >
                                                                                                                          {/* Header */}
                                                                                                                                <div className="flex w-full justify-between items-center max-w-5xl mb-8">
                                                                                                                                        <h1 className="text-2xl font-bold">🚀 FREP Launchpad</h1>
                                                                                                                                                <div className="flex items-center gap-4">
                                                                                                                                                          <button
                                                                                                                                                                      onClick={toggleTheme}
                                                                                                                                                                                  className="p-2 rounded-full bg-gray-200 dark:bg-gray-700"
                                                                                                                                                                                            >
                                                                                                                                                                                                        {theme === "light" ? <Moon size={20} /> : <Sun size={20} />}
                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                            <WalletMultiButton />
                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                {/* Main Card */}
                                                                                                                                                                                                                                                      <div className="w-full max-w-lg bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-6 flex flex-col gap-6">
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                      {/* Wallet Info */}
                                                                                                                                                                                                                                                                              {connected && publicKey && (
                                                                                                                                                                                                                                                                                        <div className="text-center">
                                                                                                                                                                                                                                                                                                    <p className="text-sm">
                                                                                                                                                                                                                                                                                                                  <span className="font-medium">Connected:</span>{" "}
                                                                                                                                                                                                                                                                                                                                <span className="font-mono">
                                                                                                                                                                                                                                                                                                                                                {publicKey.toBase58().slice(0, 6)}...{publicKey.toBase58().slice(-4)}
                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                    Balance:{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                  {balance !== null ? `${balance.toFixed(3)} SOL` : "..."}
                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Network Selector */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {connected && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="block mb-2 font-medium">Select Network:</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full px-4 py-2 rounded-lg border bg-white dark:bg-gray-700 dark:border-gray-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={network}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setNetwork(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {availableNetworks.map((net) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option key={net} value={net}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {net.toUpperCase()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Calculator */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="block mb-2 font-medium">Amount (SOL):</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full px-4 py-2 rounded-lg border bg-white dark:bg-gray-700 dark:border-gray-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-2 text-sm text-gray-600 dark:text-gray-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      You will receive: <span className="font-semibold">{frep} FREP</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Buy Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full py-3 bg-indigo-600 text-white rounded-xl font-semibold shadow hover:bg-indigo-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Buy Now
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }